name: Build and test libcbv2g
on: 
  pull_request: {}
  workflow_dispatch:
    inputs:
      runner:
        description: Which runner to use
        type: choice
        default: 'ubuntu-22.04'
        required: true
        options:
          - 'ubuntu-22.04'
          - 'large-ubuntu-22.04-xxl'
  schedule:
    - cron: '37 13,1 * * *'
jobs:
  ci:
    name: Build and Test
    uses: everest/everest-ci/.github/workflows/continuous_integration.yml@v1.5.2
    permissions:
      contents: read
    secrets:
      coverage_deploy_token: ""
    with:
      runner: ${{ inputs.runner || 'ubuntu-22.04' }}
      artifact_deploy_target_repo: EVerest/everest.github.io
      run_coverage: false
      run_lint: false
      do_not_run_coverage_badge_creation: true
      run_install: false
      run_install_wheels: false
      run_integration_tests: false
      ctest_report_path: ctest-report
