set(PACKAGE_VERSION 0.5.3)

if(PACKAGE_FIND_VERSION STREQUAL PACKAGE_VERSION)
    set(PACKAGE_VERSION_EXACT TRUE)
elseif (PACKAGE_FIND_VERSION_MAJOR STREQUAL "0")
    if (PACKAGE_FIND_VERSION_MINOR GREATER "5")
        set(PACKAGE_VERSION_UNSUITABLE TRUE)
    else ()
        set(PACKAGE_VERSION_COMPATIBLE TRUE)
    endif ()
else ()
    set(PACKAGE_VERSION_UNSUITABLE TRUE)
endif()

