#!/bin/bash
set -e
# remove build folder
rm -rf build
mkdir build
# clear CPM cache
rm -rf $CPM_SOURCE_CACHE/../CPM
# install up to date edm
pip install ../everest-dev-environment/dependency_manager
# install up to date ev-cli
pip install ../everest-utils/ev-dev-tools
# Run cmake
cd build
cmake ..
# update all autogenerated module files
make force_update_all_modules
# maybe that changed dependencies? run cmake again
cmake ..
# Finally we are ready to build!
make -j8
make install
