/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "mMWcar.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(EverestToMcu, EverestToMcu, AUTO)


PB_BIND(McuToEverest, McuToEverest, AUTO)


PB_BIND(KeepAlive, KeepAlive, AUTO)


PB_BIND(ACMeasInstant, ACMeasInstant, AUTO)


PB_BIND(ACMeasStats, ACMeasStats, AUTO)


PB_BIND(ACPhaseStats, ACPhaseStats, AUTO)


PB_BIND(DCMeasInstant, DCMeasInstant, AUTO)


PB_BIND(BootConfigRequest, BootConfigRequest, AUTO)


PB_BIND(BootConfigResponse, BootConfigResponse, AUTO)


PB_BIND(ErrorFlags, ErrorFlags, AUTO)


PB_BIND(CalibrationRequest, CalibrationRequest, AUTO)


PB_BIND(CalibrationResponse, CalibrationResponse, AUTO)


PB_BIND(CalibrationValues, CalibrationValues, 2)


PB_BIND(AC_Calibration, AC_Calibration, AUTO)


PB_BIND(BasicChargingCommMeasInstant, BasicChargingCommMeasInstant, AUTO)


PB_BIND(Adc_Raw, Adc_Raw, AUTO)










#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

