[package]
name = "RsPaymentTerminal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
everestrs = { workspace=true }
anyhow = "1.0.82"
zvt = { git = "https://github.com/Everest/zvt.git", rev = "60574939d2cbe35b5d4fc9b03af7e8c3e098706c" }
zvt_feig_terminal = { git = "https://github.com/Everest/zvt.git", rev = "60574939d2cbe35b5d4fc9b03af7e8c3e098706c", features = ["with_lavego_error_codes"] }
tokio = { version = "1.47.0", features = ["macros", "rt-multi-thread", "net", "sync"] }
log = "0.4.20"
mockall = { version = "0.12.1", optional = true }
mockall_double = { version = "0.3.1", optional = true}

[build-dependencies]
everestrs-build = { workspace=true }

[features]
with_lavego_error_codes = ["zvt_feig_terminal/with_lavego_error_codes"]
default = ["mockall", "mockall_double", "with_lavego_error_codes"]
