AllowOfflineTxForUnknownId:
  module_id: allow_offline_tx_for_unknown_id
  config_key: allow_offline_tx_for_unknown_id_config
AuthorizationCacheEnabled:
  module_id: authorization_cache_enabled
  config_key: authorization_cache_enabled_config
AuthorizeRemoteTxRequests:
  module_id: authorize_remote_tx_requests
  config_key: authorize_remote_tx_requests_config
BlinkRepeat:
  module_id: blink_repeat
  config_key: blink_repeat_config
ClockAlignedDataInterval:
  module_id: clock_aligned_data_interval
  config_key: clock_aligned_data_interval_config
ConnectionTimeOut:
  module_id: connection_time_out
  config_key: connection_time_out_config
ConnectorPhaseRotation:
  module_id: connector_phase_rotation
  config_key: connector_phase_rotation_config
HeartbeatInterval:
  module_id: heartbeat_interval
  config_key: heartbeat_interval_config
LightIntensity:
  module_id: light_intensity
  config_key: light_intensity_config
LocalAuthorizeOffline:
  module_id: local_authorize_offline
  config_key: local_authorize_offline_config
LocalPreAuthorize:
  module_id: local_pre_authorize
  config_key: local_pre_authorize_config
MaxEnergyOnInvalidId:
  module_id: max_energy_on_invalid_id
  config_key: max_energy_on_invalid_id_config
MeterValuesAlignedData:
  module_id: meter_values_aligned_data
  config_key: meter_values_aligned_data_config
MeterValuesSampledData:
  module_id: meter_values_sampled_data
  config_key: meter_values_sampled_data_config
MeterValueSampleInterval:
  module_id: meter_value_sample_interval
  config_key: meter_value_sample_interval_config
MinimumStatusDuration:
  module_id: minimum_status_duration
  config_key: minimum_status_duration_config
ResetRetries:
  module_id: reset_retries
  config_key: reset_retries_config
StopTransactionOnEVSideDisconnect:
  module_id: stop_transaction_on_ev_side_disconnect
  config_key: stop_transaction_on_ev_side_disconnect_config
StopTransactionOnInvalidId:
  module_id: stop_transaction_on_invalid_id
  config_key: stop_transaction_on_invalid_id_config
StopTxnAlignedData:
  module_id: stop_txn_aligned_data
  config_key: stop_txn_aligned_data_config
StopTxnSampledData:
  module_id: stop_txn_sampled_data
  config_key: stop_txn_sampled_data_config
TransactionMessageAttempts:
  module_id: transaction_message_attempts
  config_key: transaction_message_attempts_config
TransactionMessageRetryInterval:
  module_id: transaction_message_retry_interval
  config_key: transaction_message_retry_interval_config
UnlockConnectorOnEVSideDisconnect:
  module_id: unlock_connector_on_ev_side_disconnect
  config_key: unlock_connector_on_ev_side_disconnect_config
WebsocketPingInterval:
  module_id: websocket_ping_interval
  config_key: websocket_ping_interval_config
