/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "lo2hi.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(LoToHi, LoToHi, AUTO)


PB_BIND(Event, Event, AUTO)


PB_BIND(SimulationFeedback, SimulationFeedback, AUTO)


PB_BIND(PowerMeter, PowerMeter, AUTO)


PB_BIND(KeepAliveLo, KeepAliveLo, AUTO)


PB_BIND(StateUpdate, StateUpdate, AUTO)


PB_BIND(ErrorFlags, ErrorFlags, AUTO)


PB_BIND(ChargingFlags, ChargingFlags, AUTO)


PB_BIND(ResetDone, ResetDone, AUTO)


PB_BIND(DebugUpdate, DebugUpdate, AUTO)







