/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "hi2lo.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(HiToLo, HiToLo, AUTO)


PB_BIND(AllowPowerOn, AllowPowerOn, AUTO)


PB_BIND(SetOutputVoltageCurrent, SetOutputVoltageCurrent, AUTO)


PB_BIND(SetPWM, SetPWM, AUTO)


PB_BIND(FirmwareUpdate, FirmwareUpdate, AUTO)


PB_BIND(KeepAliveHi, KeepAliveHi, AUTO)


PB_BIND(Replug, Replug, AUTO)


PB_BIND(Enable, Enable, AUTO)


PB_BIND(Disable, Disable, AUTO)


PB_BIND(Reset, Reset, AUTO)



