PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS CONNECTORS (
    ID INT PRIMARY KEY NOT NULL,
    AVAILABILITY TEXT
);
CREATE TABLE IF NOT EXISTS AUTH_CACHE (
    ID_TAG TEXT PRIMARY KEY NOT NULL,
    AUTH_STATUS TEXT NOT NULL,
    EXPIRY_DATE TEXT,
    PARENT_ID_TAG TEXT
);
CREATE TABLE IF NOT EXISTS AUTH_LIST_VERSION (
    ID INT PRIMARY KEY NOT NULL,
    VERSION INT
);
CREATE TABLE IF NOT EXISTS AUTH_LIST (
    ID_TAG TEXT PRIMARY KEY NOT NULL,
    AUTH_STATUS TEXT NOT NULL,
    EXPIRY_DATE TEXT,
    PARENT_ID_TAG TEXT
);
CREATE TABLE IF NOT EXISTS TRANSACTIONS (
    ID INT PRIMARY KEY NOT NULL,
    TRANSACTION_ID INT,
    CONNECTOR INT NOT NULL,
    ID_TAG_START TEXT NOT NULL,
    TIME_START TEXT NOT NULL,
    METER_START INT NOT NULL,
    RESERVATION_ID INT,
    PARENT_ID_TAG TEXT,
    ID_TAG_END TEXT,
    TIME_END TEXT,
    METER_STOP INT,
    STOP_REASON TEXT,
    FOREIGN KEY(CONNECTOR) REFERENCES CONNECTORS(ID)
);
CREATE TABLE IF NOT EXISTS SCHEDULED_CALLBACKS (
    ID INT PRIMARY KEY NOT NULL,
    CALLBACK TEXT,
    SCHEDULED_DATE TEXT
);
INSERT
    OR IGNORE INTO AUTH_LIST_VERSION (ID, VERSION)
VALUES (0, 0);
