active_modules:
  iso15118_ev:
    module: PyEvJosev
    config_module:
      device: eth1
      supported_ISO15118_2: true
      tls_active: false
  mMWcar:
    module: mMWcarBSP
    config_module:
      serial_port: /dev/serial0
  ev_slac:
    module: EvSlac
    config_implementation:
      main:
        device: eth1
  ev_manager:
    module: EvManager
    config_module:
      connector_id: 1
      auto_enable: true
      auto_exec: true
      auto_exec_infinite: false
      auto_exec_commands: wait_for_real_plugin;iso_wait_pwm_is_running;iso_wait_slac_matched;iso_start_v2g_session AC;iso_wait_pwr_ready;sleep 1;iso_draw_power_regulated 16,1;iso_wait_for_stop 20;iso_wait_v2g_session_stopped;unplug;sleep 30;
      dc_target_current: 1
      dc_target_voltage: 200    
    connections:
      ev_board_support:
        - module_id: mMWcar
          implementation_id: simple_board_support
      ev:
        - module_id: iso15118_ev
          implementation_id: ev
      slac:
        - module_id: ev_slac
          implementation_id: main
x-module-layout: {}
