active_modules:
  iso15118_charger_1:
    module: EvseV2G
    config_module:
      device: br-e2d7d9df05a1
      tls_security: allow
    connections:
      security:
        - module_id: evse_security
          implementation_id: main
  iso15118_car_1:
    module: PyEvJosev
    config_module:
      device: br-e2d7d9df05a1
      supported_DIN70121: true
      supported_ISO15118_2: true
  iso15118_charger_2:
    module: EvseV2G
    config_module:
      device: veth1
      tls_security: allow
    connections:
      security:
        - module_id: evse_security
          implementation_id: main
  iso15118_car_2:
    module: PyEvJosev
    config_module:
      device: veth1
      supported_DIN70121: true
      supported_ISO15118_2: true
  persistent_store:
    module: PersistentStore
  evse_manager_1:
    module: EvseManager
    mapping:
      module:
        evse: 1
    config_module:
      connector_id: 1
      evse_id: DE*PNX*E12345*1
      evse_id_din: 49A80737A45678
      session_logging: true
      session_logging_xml: false
      session_logging_path: /tmp/everest-logs
      external_ready_to_start_charging: true
      charge_mode: DC
      payment_enable_contract: false
      request_zero_power_in_idle: true
      raise_mrec9: false
    connections:
      bsp:
        - module_id: yeti_driver_1
          implementation_id: board_support
      powermeter_car_side:
        - module_id: powersupply_dc_1
          implementation_id: powermeter
      slac:
        - module_id: slac_1
          implementation_id: evse
      hlc:
        - module_id: iso15118_charger_1
          implementation_id: charger
      powersupply_DC:
        - module_id: powersupply_dc_1
          implementation_id: main
      imd:
        - module_id: imd_1
          implementation_id: main
      store:
        - module_id: persistent_store
          implementation_id: main
  evse_manager_2:
    module: EvseManager
    mapping:
      module:
        evse: 2
    config_module:
      connector_id: 2
      evse_id: DE*PNX*E12345*2
      evse_id_din: 49A80737A45679
      session_logging: true
      session_logging_xml: false
      session_logging_path: /tmp/everest-logs/evse2
      external_ready_to_start_charging: true
      charge_mode: DC
      payment_enable_contract: false
      request_zero_power_in_idle: true
      raise_mrec9: false
    connections:
      bsp:
        - module_id: yeti_driver_2
          implementation_id: board_support
      powermeter_car_side:
        - module_id: powersupply_dc_2
          implementation_id: powermeter
      slac:
        - module_id: slac_2
          implementation_id: evse
      hlc:
        - module_id: iso15118_charger_2
          implementation_id: charger
      powermeter_grid_side:
        - module_id: yeti_driver_2
          implementation_id: powermeter
      powersupply_DC:
        - module_id: powersupply_dc_2
          implementation_id: main
      imd:
        - module_id: imd_2
          implementation_id: main
      store:
        - module_id: persistent_store
          implementation_id: main
  ocpp:
    module: OCPP
    config_module:
      ChargePointConfigPath: config-full.json
    connections:
      evse_manager:
        - module_id: evse_manager_1
          implementation_id: evse
        - module_id: evse_manager_2
          implementation_id: evse
      reservation:
        - module_id: auth
          implementation_id: reservation
      auth:
        - module_id: auth
          implementation_id: main
      system:
        - module_id: system
          implementation_id: main
      security:
        - module_id: evse_security
          implementation_id: main
      display_message:
        - module_id: display_message
          implementation_id: display_message
      evse_energy_sink:
        - module_id: grid_connection_point
          implementation_id: external_limits
        - module_id: evse_manager_1_ocpp_sink
          implementation_id: external_limits
        - module_id: evse_manager_2_ocpp_sink
          implementation_id: external_limits
      extensions_15118:
        - module_id: iso15118_charger_1
          implementation_id: extensions
        - module_id: iso15118_charger_2
          implementation_id: extensions
  display_message:
    module: TerminalDisplayMessage
  session_cost:
    module: TerminalCostAndPriceMessage
    connections:
      session_cost:
        - module_id: ocpp
          implementation_id: session_cost
  evse_manager_1_ocpp_sink:
    module: EnergyNode
    mapping:
      module:
        evse: 1
    config_module:
      fuse_limit_A: 32.0
      phase_count: 3
    connections:
      energy_consumer:
        - module_id: evse_manager_1
          implementation_id: energy_grid
  evse_manager_2_ocpp_sink:
    module: EnergyNode
    mapping:
      module:
        evse: 2
    config_module:
      fuse_limit_A: 32.0
      phase_count: 3
    connections:
      energy_consumer:
        - module_id: evse_manager_2
          implementation_id: energy_grid
  evse_manager_1_api_sink:
    module: EnergyNode
    mapping:
      module:
        evse: 1
    config_module:
      fuse_limit_A: 32.0
      phase_count: 3
    connections:
      energy_consumer:
        - module_id: evse_manager_1_ocpp_sink
          implementation_id: energy_grid
      powermeter:
        - module_id: yeti_driver_1
          implementation_id: powermeter
  evse_manager_2_api_sink:
    module: EnergyNode
    mapping:
      module:
        evse: 2
    config_module:
      fuse_limit_A: 32.0
      phase_count: 3
    connections:
      energy_consumer:
        - module_id: evse_manager_2_ocpp_sink
          implementation_id: energy_grid
      powermeter:
        - module_id: yeti_driver_2
          implementation_id: powermeter
  yeti_driver_1:
    module: YetiSimulator
    mapping:
      module:
        evse: 1
    config_module:
      connector_id: 1
  yeti_driver_2:
    module: YetiSimulator
    mapping:
      module:
        evse: 2
    config_module:
      connector_id: 2
  slac_1:
    module: SlacSimulator
  slac_2:
    module: SlacSimulator
  powersupply_dc_1:
    module: DCSupplySimulator
  powersupply_dc_2:
    module: DCSupplySimulator
  imd_1:
    module: IMDSimulator
    config_implementation:
      main:
        selftest_success: true
  imd_2:
    module: IMDSimulator
    config_implementation:
      main:
        selftest_success: true
  ev_manager_1:
    module: EvManager
    config_module:
      connector_id: 1
      auto_enable: true
      auto_exec: false
      auto_exec_commands: sleep 1;iec_wait_pwr_ready;sleep 60
      dc_target_current: 20
      dc_target_voltage: 400
      keep_cross_boot_plugin_state: true
    connections:
      ev_board_support:
        - module_id: yeti_driver_1
          implementation_id: ev_board_support
      ev:
        - module_id: iso15118_car_1
          implementation_id: ev
      slac:
        - module_id: slac_1
          implementation_id: ev
      kvs:
        - module_id: persistent_store
          implementation_id: main
  ev_manager_2:
    module: EvManager
    config_module:
      connector_id: 2
      auto_enable: true
      auto_exec: false
      auto_exec_commands: sleep 1;iec_wait_pwr_ready;sleep 60
      dc_target_current: 20
      dc_target_voltage: 400
      keep_cross_boot_plugin_state: true
    connections:
      ev_board_support:
        - module_id: yeti_driver_2
          implementation_id: ev_board_support
      ev:
        - module_id: iso15118_car_2
          implementation_id: ev
      slac:
        - module_id: slac_2
          implementation_id: ev
      kvs:
        - module_id: persistent_store
          implementation_id: main
  auth:
    module: Auth
    config_module:
      connection_timeout: 10
      selection_algorithm: FindFirst
    connections:
      token_provider:
        - module_id: token_provider_1
          implementation_id: main
        - module_id: ocpp
          implementation_id: auth_provider
      token_validator:
        - module_id: ocpp
          implementation_id: auth_validator
      evse_manager:
        - module_id: evse_manager_1
          implementation_id: evse
        - module_id: evse_manager_2
          implementation_id: evse
      kvs:
        - module_id: persistent_store
          implementation_id: main
  evse_security:
    module: EvseSecurity
    config_module:
      private_key_password: "123456"
  token_provider_1:
    module: DummyTokenProviderManual
  energy_manager:
    module: EnergyManager
    connections:
      energy_trunk:
        - module_id: grid_connection_point
          implementation_id: energy_grid
  grid_connection_point:
    module: EnergyNode
    mapping:
      module:
        evse: 0
    config_module:
      fuse_limit_A: 40.0
      phase_count: 3
    connections:
      price_information: []
      energy_consumer:
        - module_id: evse_manager_1_api_sink
          implementation_id: energy_grid
        - module_id: evse_manager_2_api_sink
          implementation_id: energy_grid
      powermeter:
        - module_id: yeti_driver_1
          implementation_id: powermeter
  api:
    module: API
    connections:
      evse_manager:
        - module_id: evse_manager_1
          implementation_id: evse
        - module_id: evse_manager_2
          implementation_id: evse
      ocpp:
        - module_id: ocpp
          implementation_id: ocpp_generic
      evse_energy_sink:
        - module_id: evse_manager_1_api_sink
          implementation_id: external_limits
        - module_id: evse_manager_2_api_sink
          implementation_id: external_limits
      error_history:
        - module_id: error_history
          implementation_id: error_history
  error_history:
    module: ErrorHistory
    config_implementation:
      error_history:
        database_path: /tmp/error_history.db
  system:
    module: System
    config_module:
      ResetDelay: 1
    connections:
      store:
        - module_id: persistent_store
          implementation_id: main
x-module-layout: {}
