active_modules:
  iso15118_charger_1:
    module: PyJosev
    config_module:
      device: auto
  iso15118_car_1:
    module: JsCarV2G
    config_implementation:
      main:
        stack_implementation: RISE-V2G
        mqtt_base_path: everest_external/iso15118/ev_1
        device: auto
  evse_manager_1:
    module: EvseManager
    config_module:
      connector_id: 1
      three_phases: true
      has_ventilation: true
      country_code: DE
      rcd_enabled: true
      evse_id: DE*PNX*E12345*1
      session_logging: true
      session_logging_xml: false
      session_logging_path: /tmp
      ac_hlc_enabled: false
      ac_hlc_use_5percent: false
      ac_enforce_hlc: false
    connections:
      bsp:
        - module_id: yeti_driver_1
          implementation_id: board_support
      powermeter_grid_side:
        - module_id: yeti_driver_1
          implementation_id: powermeter
  evse_manager_2:
    module: EvseManager
    config_module:
      connector_id: 2
      three_phases: true
      has_ventilation: true
      country_code: DE
      rcd_enabled: true
      evse_id: DE*PNX*E12345*2
      session_logging: true
      session_logging_xml: false
      session_logging_path: /tmp
      ac_hlc_enabled: false
      ac_hlc_use_5percent: false
      ac_enforce_hlc: false
    connections:
      bsp:
        - module_id: yeti_driver_2
          implementation_id: board_support
      powermeter_grid_side:
        - module_id: yeti_driver_2
          implementation_id: powermeter
  evse_manager_3:
    module: EvseManager
    config_module:
      connector_id: 3
      three_phases: true
      has_ventilation: true
      country_code: DE
      rcd_enabled: true
      evse_id: DE*PNX*E12345*3
      session_logging: true
      session_logging_xml: false
      session_logging_path: /tmp
      ac_hlc_enabled: false
      ac_hlc_use_5percent: false
      ac_enforce_hlc: false
    connections:
      bsp:
        - module_id: yeti_driver_3
          implementation_id: board_support
      powermeter_grid_side:
        - module_id: yeti_driver_3
          implementation_id: powermeter
  evse_manager_4:
    module: EvseManager
    config_module:
      connector_id: 4
      three_phases: true
      has_ventilation: true
      country_code: DE
      rcd_enabled: true
      evse_id: DE*PNX*E12345*4
      session_logging: true
      session_logging_xml: false
      session_logging_path: /tmp
      ac_hlc_enabled: false
      ac_hlc_use_5percent: false
      ac_enforce_hlc: false
    connections:
      bsp:
        - module_id: yeti_driver_4
          implementation_id: board_support
      powermeter_grid_side:
        - module_id: yeti_driver_4
          implementation_id: powermeter
  yeti_driver_1:
    module: JsYetiSimulator
  yeti_driver_2:
    module: JsYetiSimulator
  yeti_driver_3:
    module: JsYetiSimulator
  yeti_driver_4:
    module: JsYetiSimulator
  slac_1:
    module: JsSlacSimulator
  car_simulator_1:
    module: JsCarSimulator
    config_module:
      connector_id: 1
      auto_enable: true
      auto_exec: true
      auto_exec_commands: sleep 5;iec_wait_pwr_ready;sleep 1;draw_power_regulated 16,3;sleep 36000;unplug
    connections:
      simulation_control:
        - module_id: yeti_driver_1
          implementation_id: yeti_simulation_control
  car_simulator_2:
    module: JsCarSimulator
    config_module:
      connector_id: 2
      auto_enable: true
      auto_exec: true
      auto_exec_commands: sleep 5;iec_wait_pwr_ready;sleep 1;draw_power_regulated 16,3;sleep 36000;unplug
    connections:
      simulation_control:
        - module_id: yeti_driver_2
          implementation_id: yeti_simulation_control
  car_simulator_3:
    module: JsCarSimulator
    config_module:
      connector_id: 3
      auto_enable: true
      auto_exec: true
      auto_exec_commands: sleep 7;iec_wait_pwr_ready;sleep 1;draw_power_regulated 16,3;sleep 36000;unplug
    connections:
      simulation_control:
        - module_id: yeti_driver_3
          implementation_id: yeti_simulation_control
  car_simulator_4:
    module: JsCarSimulator
    config_module:
      connector_id: 4
      auto_enable: true
      auto_exec: true
      auto_exec_commands: sleep 8;iec_wait_pwr_ready;sleep 1;draw_power_regulated 16,3;sleep 36000;unplug
    connections:
      simulation_control:
        - module_id: yeti_driver_4
          implementation_id: yeti_simulation_control
  auth:
    module: Auth
    config_module:
      connection_timeout: 10
      selection_algorithm: PlugEvents
    connections:
      token_provider:
        - module_id: token_provider_1
          implementation_id: main
        - module_id: token_provider_2
          implementation_id: main
        - module_id: token_provider_3
          implementation_id: main
        - module_id: token_provider_4
          implementation_id: main
      token_validator:
        - module_id: token_validator
          implementation_id: main
      evse_manager:
        - module_id: evse_manager_1
          implementation_id: evse
        - module_id: evse_manager_2
          implementation_id: evse
        - module_id: evse_manager_3
          implementation_id: evse
        - module_id: evse_manager_4
          implementation_id: evse
  token_provider_1:
    module: JsDummyTokenProvider
    connections:
      evse:
        - module_id: evse_manager_1
          implementation_id: evse
    config_implementation:
      main:
        type: dummy
        token: CARD1
  token_provider_2:
    module: JsDummyTokenProvider
    connections:
      evse:
        - module_id: evse_manager_2
          implementation_id: evse
    config_implementation:
      main:
        type: dummy
        token: CARD2
  token_provider_3:
    module: JsDummyTokenProvider
    connections:
      evse:
        - module_id: evse_manager_3
          implementation_id: evse
    config_implementation:
      main:
        type: dummy
        token: CARD3
  token_provider_4:
    module: JsDummyTokenProvider
    connections:
      evse:
        - module_id: evse_manager_4
          implementation_id: evse
    config_implementation:
      main:
        type: dummy
        token: CARD4
  token_validator:
    module: JsDummyTokenValidator
    config_implementation:
      main:
        validation_result: Accepted
        validation_reason: Token seems valid
        sleep: 0.25
  energy_manager:
    module: EnergyManager
    connections:
      energy_trunk:
        - module_id: grid_connection_point
          implementation_id: energy_grid
  grid_connection_point:
    module: EnergyNode
    config_module:
      fuse_limit_A: 40.0
      phase_count: 3
    connections:
      price_information: []
      energy_consumer:
        - module_id: evse_manager_1
          implementation_id: energy_grid
        - module_id: evse_manager_2
          implementation_id: energy_grid
        - module_id: evse_manager_3
          implementation_id: energy_grid
        - module_id: evse_manager_4
          implementation_id: energy_grid
      powermeter:
        - module_id: yeti_driver_1
          implementation_id: powermeter
  api:
    module: API
    connections:
      evse_manager:
        - module_id: evse_manager_1
          implementation_id: evse
x-module-layout: {}
