auth:
  module: JsAuth
  connections:
    tokenProvider:
      - module_id: token_provider_1
        implementation_id: main
      - module_id: token_provider_2
        implementation_id: main
    tokenValidator:
      - module_id: token_validator
        implementation_id: main
token_provider_1:
  module: JsDummyTokenProvider
  config_implementation:
    main:
      sleep: 2
      type: dummy
token_provider_2:
  module: JsDummyTokenProvider
  config_implementation:
    main:
      sleep: 5
      type: cool
token_validator:
  module: JsDummyTokenValidator
  config_implementation:
    main:
      validation_result: Accepted
      validation_reason: Token seems valid
      sleep: 0.25
