settings:
  telemetry_enabled: true
active_modules:
  store:
    module: Store
  example:
    config_implementation:
      example:
        current: 42
        enum_test: one
        enum_test2: 2
    connections:
      kvs:
        - module_id: store
          implementation_id: main
    module: Example
  example_user:
    connections:
      example:
        - module_id: example
          implementation_id: example
      example_multiple:
        - module_id: example
          implementation_id: example_multiple.0 # TODO: use .0 ... .127 index syntax
        - module_id: example
          implementation_id: example_multiple.1
        # - module_id: example
        #   implementation_id: example_multiple.2
    module: ExampleUser
