[package]
name = "dep_tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.12"
serde = { version = "1.0.197", features = ["derive"] }
serde_derive = "1.0.197"
serde_yaml = "0.9.32"
