@startuml
autonumber "<b><font color=red>"
participant Powermeter
participant EvseManager
participant OCPP
participant CSMS

title Start of a Transaction

== User plugs in EV and authorizes ==

EvseManager->OCPP: Event(SessionStarted)

OCPP->CSMS: StatusNotification.req(Preparing)
return StatusNotification.conf

alt successful case
    EvseManager -> Powermeter: startTransaction
    return startTransaction Response (OK/ID)

    EvseManager -> OCPP: Event(TransactionStarted)
    OCPP->CSMS: StartTransaction.req
    return StartTransaction.conf

    note over EvseManager: Transaction started successfully

else startTransaction failing due to power loss
    EvseManager -> Powermeter: startTransaction
    return startTransaction Response (FAIL)

    EvseManager -> OCPP: Event(Deauthorized)

    OCPP->CSMS: StatusNotification.req(Finishing)
    return StatusNotification.conf

    EvseManager -> OCPP: raiseError (PowermeterTransactionStartFailed)
    OCPP->CSMS: StatusNotification.req(Finishing, PowermeterTransactionStartFailed)
    return StatusNotification.conf

alt EvseManager configured to become inoperative in case of PowermeterCommError
    EvseManager -> OCPP: raiseError (Inoperative)
    OCPP->CSMS: StatusNotification.req(Faulted)
    return StatusNotification.conf

end

note over EvseManager: Transaction did not start

end

@enduml
