[package]
name = "RsLedDriver"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
everestrs = { workspace=true }
log = "0.4.20"

[build-dependencies]
everestrs-build = { workspace=true }
