[workspace]
resolver = "2"
members = [
   "RsExample",
   "RsExampleUser",
]

[workspace.dependencies]
everestrs = { git = "https://github.com/qwello/everest-framework.git", rev = "06983df646695303017137d00eea9f63b808fd71" }
everestrs-build = { git = "https://github.com/qwello/everest-framework.git", rev = "06983df646695303017137d00eea9f63b808fd71" }
