[workspace]
resolver = "2"
members = [
   "RsExample",
   "RsExampleUser",
]

[workspace.dependencies]
everestrs = { git = "https://github.com/everest/everest-framework.git", rev = "21b5371ec38158ddfcbe9eea0f92a18154ca3c76" }
everestrs-build = { git = "https://github.com/everest/everest-framework.git", rev = "21b5371ec38158ddfcbe9eea0f92a18154ca3c76" }
