[workspace]
resolver = "2"
members = [
   "RsExample",
   "RsExampleUser",
]

[workspace.dependencies]
everestrs = { git = "https://github.com/qwello/everest-framework.git", rev = "64411bbc78b94e9d1d28f421bf0f3a8adb0dca92" }
everestrs-build = { git = "https://github.com/qwello/everest-framework.git", rev = "64411bbc78b94e9d1d28f421bf0f3a8adb0dca92" }
