settings:
  telemetry_enabled: false
active_modules:
  bsp:
    config_module:
      connector_id: 1
    module: YetiSimulator
  cli:
    connections:
      bsp:
        - implementation_id: board_support
          module_id: bsp
    module: BUEvseBoardSupport
