settings:
  telemetry_enabled: false

active_modules:
  slac:
    module: EvseSlac
    config_implementation:
      main:
        device: tap0
        link_status_detection: true
        set_key_timeout_ms: 50000
