settings:
  telemetry_enabled: false
active_modules:
  slac_api:
    module: slac_API
    config_module:
      cfg_communication_check_to_s: 0
  cli:
    module: BUSlac
    standalone: true
    connections:
      slac:
        - module_id: slac_api
          implementation_id: main
