settings:
  telemetry_enabled: false
active_modules:
  system:                                                                                             
    module: System
    connections:
      store:
        - module_id: persistent_store
          implementation_id: main
  persistent_store:
    config_module:
      sqlite_db_file_path: everest_persistent_store.db
    connections: {}
    module: PersistentStore
  cli:
    module: BUSystem
    connections:
      system: 
        - module_id: system
          implementation_id: main
