settings:
  telemetry_enabled: false
active_modules:
  bsp_1:
    module: evse_board_support_API
    config_module:
      cfg_communication_check_to_s: 0
      cfg_heartbeat_interval_ms: 1000
  ovm_1:
    module: over_voltage_monitor_API
    config_module:
      cfg_communication_check_to_s: 0
      cfg_heartbeat_interval_ms: 1000

  bsp_ui:
    module: BUEvseBoardSupport
    standalone: true
    connections:
      bsp:
        - module_id: bsp_1
          implementation_id: main
  ovm_ui:
    module: BUOverVoltageMonitor
    standalone: true
    connections:
      ovm:
        - module_id: ovm_1
          implementation_id: main
