settings:
  telemetry_enabled: false
active_modules:
  dm_1:
    module: display_message_API
    config_module:
      cfg_communication_check_to_s: 5
  cli:
    module: BUDisplayMessage
    standalone: true
    connections:
      dm:
        - module_id: dm_1
          implementation_id: main
