settings:
  telemetry_enabled: false
active_modules:
  powermeter:
    config_module:
      ip_address: "192.168.1.2"
    module: LemDCBM400600
    standalone: true
  cli:
    config_module:
      evse_id: "my_evse"
    module: BUPowermeter
    standalone: true
    connections:
      powermeter:
        - module_id: powermeter
          implementation_id: main
