settings:
  telemetry_enabled: false
active_modules:
  bsp:
    module: mMWcarBSP
#    standalone: true
    config_module:
      baud_rate: 115200
      serial_port: /dev/ttyACM0
#      serial_port: /dev/pts/5
  cli:
    module: BUmMWcar
    standalone: true
    connections:
      board_support:
        - module_id: bsp
          implementation_id: simple_board_support
      board_support_extended:
        - module_id: bsp
          implementation_id: board_support_extended
