name: "Build CI Testing Base Image"
on:
  workflow_dispatch:
jobs:
  test_A:
    name: "Build EVerest CI Testing Base Image"
    runs-on: ubuntu-22.04
    permissions:
      actions: read
      packages: write
    steps:
          
      - uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: 'EVerest'
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ci/Dockerfile
          push: true
          tags: ghcr.io/everest/automated-ci-testing-base-image