name: Dagger Build, Lint and Test
on:
  pull_request: {}
  merge_group: {}
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      runner:
        description: Which runner to use
        type: choice
        default: 'ubuntu-24.04'
        required: true
        options:
          - 'ubuntu-24.04'
          - 'large-ubuntu-22.04-xxl'
  schedule:
    - cron: '12 13,1 * * *'

jobs:
  dagger:
    name: Dagger Build, Lint and Test
    runs-on: ${{ inputs.runner || 'ubuntu-24.04' }}
    permissions:
      contents: write
      pull-requests: write
      actions: write
      checks: write
      statuses: write
      id-token: write
      issues: write
      deployments: write
      discussions: write
      pages: write
    steps:
      - name: Restore Cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ github.workspace }}/outputs/cache
          key: cache-${{ github.ref_name }}-${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: |
            cache-${{ github.ref_name }}-${{ github.run_id }}-
            cache-${{ github.ref_name }}-
            cache-
      - name: Initialize empty cache if necessary
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: |
          mkdir -p ${{ github.workspace }}/outputs/cache/ccache
          mkdir -p ${{ github.workspace }}/outputs/cache/CPM
      - name: Call Dagger
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: 0.18.12
          workdir: ${{ github.workspace }}
          module: github.com/${{ github.repository}}@${{ github.ref }}
          call: --cache-dir ${{ github.workspace }}/outputs/cache --is-github-run --github-token ${{ secrets.GITHUB_TOKEN }} --org-name ${{ github.repository_owner }} --repo-name ${{ github.event.repository.name }} --sha ${{ github.sha }} --run-id ${{ github.run_id }} --attempt-number ${{ github.run_attempt }} pull-request outputs export --path ${{ github.workspace }}/outputs
      - name: Save Cache
        if: contains(fromJSON('["schedule","push","pull_request"]'), github.event_name)
        uses: actions/cache/save@v4
        with:
          key: cache-${{ github.ref_name }}-${{ github.run_id }}-${{ github.run_attempt }}
          path: ${{ github.workspace }}/outputs/cache
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: all-artifacts
          path: ${{ github.workspace }}/outputs/artifacts
